backend:
  name: git-gateway
  branch: master
media_folder: static/img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Project'
    name: 'blog'
    folder: 'content/blogPosts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - { label: 'Tag', name: 'tag', widget: 'string' }
      - { label: 'Awwwards', name: 'awwwards', widget: 'list', field: {label: 'Name', name: 'name', widget: 'string'} }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Commisioned by', name: 'commisioned-by', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
